/** Mirrors backend `src/constants/permissions.ts` — used for UI gating. */
export const PermissionsList = {
  OFFERS_READ: 'offers.read',
  ORDERS_READ: 'orders.read',
  ORDERS_CREATE: 'orders.create',
  ORDERS_UPDATE: 'orders.update',
  ORDERS_MATERIALS_ADD: 'orders.materials.add',
  ORDERS_STATUS_CHANGE: 'orders.status.change',
  ORDERS_ASSIGNMENT_MANAGE: 'orders.assignment.manage',
  ORDERS_MEDIA_ADD: 'orders.media.add',
  ORDERS_MEDIA_DELETE: 'orders.media.delete',
  ORDERS_COMMENT_ADD: 'orders.comment.add',
  ORDERS_TIMER_USE: 'orders.timer.use',
  ORDERS_TIMER_STOP: 'orders.timer.stop',
  ORDERS_TIMERS_GLOBAL_READ: 'orders.timers.global.read',
  ORDERS_DELETE: 'orders.delete',
  ORDERS_OFFER_CLOSE: 'orders.offer.close',
  USERS_READ: 'users.read',
  USERS_MANAGE: 'users.manage',
  USERS_PERMISSIONS_MANAGE: 'users.permissions.manage',
  USERS_AUDIT_READ: 'users.audit.read',
  SELF_OFFERS_READ: 'self.offers.read',
  SELF_ORDERS_READ: 'self.orders.read',
  SELF_ORDERS_MESSAGES_WRITE: 'self.orders.messages.write',
};
